// packages/app-react-router/app/routes/mpa.tsx
import { testData } from '../../../testdata/src/ssr'
import type { Route } from './+types/mpa'

export async function loader() {
  const data = await testData()
  return { data }
}

export default function MpaPage({ loaderData }: Route.ComponentProps) {
  return (
    <table>
      <tbody>
        {loaderData.data.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <a href={`/mpa/detail?id=${entry.id}`}>View →</a>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

// packages/app-nuxt/app/pages/mpa/index.vue
<script setup lang="ts">
import { testData } from '../../../../testdata/src/ssr'

const { data } = await useAsyncData(() => testData(), { deep: false })
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in data" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
        <td>
          <a :href="`/mpa/detail?id=${entry.id}`">View →</a>
        </td>
      </tr>
    </tbody>
  </table>
</template>
