// packages/app-nuxt/app/pages/client-side-rendered/index.vue
<script setup lang="ts">
type Entry = { id: string; name: string }

const entries: Entry[] = Array.from({ length: 1000 }, () => ({
  id: crypto.randomUUID(),
  name: crypto.randomUUID(),
}))
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in entries" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
        <td>
          <NuxtLink :to="`/client-side-rendered/${entry.id}`">View →</NuxtLink>
        </td>
      </tr>
    </tbody>
  </table>
</template>

// packages/app-sveltekit/src/routes/client-side-rendered/+page.svelte
<script lang="ts">
  type Entry = { id: string; name: string }

  const entries: Entry[] = Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
</script>

<table>
  <tbody>
    {#each entries as entry (entry.id)}
      <tr>
        <td>{entry.id}</td>
        <td>{entry.name}</td>
        <td><a href="/client-side-rendered/{entry.id}">View →</a></td>
      </tr>
    {/each}
  </tbody>
</table>
