// packages/app-react-router/app/routes/server-side-rendered.tsx
import { Link } from 'react-router'
import { testData } from '../../../testdata/src/ssr'
import type { Route } from './+types/server-side-rendered'

export async function loader() {
  const data = await testData()
  return { data }
}

export default function ServerSideRenderedPage({
  loaderData,
}: Route.ComponentProps) {
  return (
    <table>
      <tbody>
        {loaderData.data.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <Link to={`/server-side-rendered/${entry.id}`}>View →</Link>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

// packages/app-solid-start/src/routes/server-side-rendered/index.tsx
import { For } from 'solid-js'
import { query, createAsync } from '@solidjs/router'
import { testData } from '../../../../testdata/src/ssr'

const getData = query(async () => {
  'use server'
  return await testData()
}, 'server-side-rendered-data')

export const route = {
  preload: () => getData(),
}

export default function ServerSideRenderedPage() {
  const data = createAsync(() => getData())

  return (
    <table>
      <tbody>
        <For each={data()}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
              <td>
                <a href={`/server-side-rendered/${entry.id}`}>View →</a>
              </td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}
