// packages/app-nuxt/app/pages/spa/result.vue
<script setup lang="ts">
definePageMeta({ ssr: false })

type Entry = { id: string; name: string }

const entries: Entry[] = Array.from({ length: 1000 }, () => ({
  id: crypto.randomUUID(),
  name: crypto.randomUUID(),
}))
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in entries" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
      </tr>
    </tbody>
  </table>
</template>

// packages/app-next-js/app/spa/result/page.tsx
'use client'

import { useState, useEffect } from 'react'

type Entry = { id: string; name: string }

function generateData(): Entry[] {
  return Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
}

export default function SpaResultPage() {
  const [entries, setEntries] = useState<Entry[] | null>(null)

  useEffect(() => {
    setEntries(generateData())
  }, [])

  if (entries === null) return null

  return (
    <table>
      <tbody>
        {entries.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
