// packages/app-nuxt/app/pages/server-side-rendered/index.vue
<script setup lang="ts">
import { testData } from '../../../../testdata/src/ssr'

const { data } = await useAsyncData(() => testData(), { deep: false })
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in data" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
        <td>
          <NuxtLink :to="`/server-side-rendered/${entry.id}`">View →</NuxtLink>
        </td>
      </tr>
    </tbody>
  </table>
</template>

// packages/app-react-router/app/routes/server-side-rendered.tsx
import { Link } from 'react-router'
import { testData } from '../../../testdata/src/ssr'
import type { Route } from './+types/server-side-rendered'

export async function loader() {
  const data = await testData()
  return { data }
}

export default function ServerSideRenderedPage({
  loaderData,
}: Route.ComponentProps) {
  return (
    <table>
      <tbody>
        {loaderData.data.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <Link to={`/server-side-rendered/${entry.id}`}>View →</Link>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
