// packages/app-solid-start/src/routes/spa/index.tsx
export const ssr = false

import { For } from 'solid-js'
import { A } from '@solidjs/router'

type Entry = { id: string; name: string }

function generateData(): Entry[] {
  return Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
}

export default function SpaPage() {
  const entries = generateData()

  return (
    <table>
      <tbody>
        <For each={entries}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
              <td>
                <A href={`/spa/detail?id=${entry.id}`}>View →</A>
              </td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}

// packages/app-react-router/app/routes/spa.tsx
import { useState } from 'react'
import { Link } from 'react-router'

type Entry = { id: string; name: string }

function generateData(): Entry[] {
  return Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
}

export default function SpaPage() {
  const [entries] = useState(generateData)

  return (
    <table>
      <tbody>
        {entries.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <Link to={`/spa/detail?id=${entry.id}`}>View →</Link>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
