// packages/app-solid-start/src/routes/ssr-throughput/index.tsx
import { For } from 'solid-js'
import { query, createAsync } from '@solidjs/router'
import { testData } from '../../../../testdata/src/ssr'

const getData = query(async () => {
  'use server'
  return await testData()
}, 'ssr-throughput-data')

export const route = {
  preload: () => getData(),
}

export default function SSRThroughputPage() {
  const data = createAsync(() => getData())

  return (
    <table>
      <tbody>
        <For each={data()}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}

// packages/app-react-router/app/routes/ssr-throughput.tsx
import { testData } from '../../../testdata/src/ssr'
import type { Route } from './+types/ssr-throughput'

export async function loader() {
  const data = await testData()
  return { data }
}

export default function SSRThroughputPage({
  loaderData,
}: Route.ComponentProps) {
  return (
    <table>
      <tbody>
        {loaderData.data.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
