// packages/app-solid-start/src/routes/ssr-throughput/index.tsx
import { For } from 'solid-js'
import { query, createAsync } from '@solidjs/router'
import { testData } from '../../../../testdata/src/ssr'

const getData = query(async () => {
  'use server'
  return await testData()
}, 'ssr-throughput-data')

export const route = {
  preload: () => getData(),
}

export default function SSRThroughputPage() {
  const data = createAsync(() => getData())

  return (
    <table>
      <tbody>
        <For each={data()}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}

// packages/app-tanstack-start-react/src/routes/ssr-throughput.tsx
import { createFileRoute } from '@tanstack/react-router'
import { testData } from '../../../testdata/src/ssr'

export const Route = createFileRoute('/ssr-throughput')({
  component: SSRThroughputPage,
  loader: async () => await testData(),
})

function SSRThroughputPage() {
  const data = Route.useLoaderData()

  return (
    <table>
      <tbody>
        {data.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
