// packages/app-nuxt/app/pages/server-side-rendered/index.vue
<script setup lang="ts">
import { testData } from '../../../../testdata/src/ssr'

const { data } = await useAsyncData(() => testData(), { deep: false })
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in data" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
        <td>
          <NuxtLink :to="`/server-side-rendered/${entry.id}`">View →</NuxtLink>
        </td>
      </tr>
    </tbody>
  </table>
</template>

// packages/app-next-js/app/server-side-rendered/page.tsx
import Link from 'next/link'
import { testData } from '../../../testdata/src/ssr'

export const dynamic = 'force-dynamic'

export default async function ServerSideRenderedPage() {
  const entries = await testData()

  return (
    <table>
      <tbody>
        {entries.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <Link href={`/server-side-rendered/${entry.id}`}>View →</Link>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}
