// packages/app-sveltekit/src/routes/spa/result/+page.svelte
<script lang="ts">
  type Entry = { id: string; name: string }

  const entries: Entry[] = Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
</script>

<table>
  <tbody>
    {#each entries as entry (entry.id)}
      <tr>
        <td>{entry.id}</td>
        <td>{entry.name}</td>
      </tr>
    {/each}
  </tbody>
</table>

// packages/app-nuxt/app/pages/spa/result.vue
<script setup lang="ts">
definePageMeta({ ssr: false })

type Entry = { id: string; name: string }

const entries: Entry[] = Array.from({ length: 1000 }, () => ({
  id: crypto.randomUUID(),
  name: crypto.randomUUID(),
}))
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in entries" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
      </tr>
    </tbody>
  </table>
</template>
