// packages/app-solid-start/src/routes/spa/result.tsx
export const ssr = false

import { For } from 'solid-js'

type Entry = { id: string; name: string }

function generateData(): Entry[] {
  return Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
}

export default function SpaResultPage() {
  const entries = generateData()

  return (
    <table>
      <tbody>
        <For each={entries}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}

// packages/app-sveltekit/src/routes/spa/result/+page.svelte
<script lang="ts">
  type Entry = { id: string; name: string }

  const entries: Entry[] = Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
</script>

<table>
  <tbody>
    {#each entries as entry (entry.id)}
      <tr>
        <td>{entry.id}</td>
        <td>{entry.name}</td>
      </tr>
    {/each}
  </tbody>
</table>
