// packages/app-sveltekit/src/routes/spa/+page.svelte
<script lang="ts">
  type Entry = { id: string; name: string }

  const entries: Entry[] = Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
</script>

<table>
  <tbody>
    {#each entries as entry (entry.id)}
      <tr>
        <td>{entry.id}</td>
        <td>{entry.name}</td>
        <td><a href="/spa/detail?id={entry.id}">View →</a></td>
      </tr>
    {/each}
  </tbody>
</table>

// packages/app-solid-start/src/routes/spa/index.tsx
import { For } from 'solid-js'
import { A } from '@solidjs/router'

export const ssr = false

type Entry = { id: string; name: string }

const entries: Entry[] = Array.from({ length: 1000 }, () => ({
  id: crypto.randomUUID(),
  name: crypto.randomUUID(),
}))

export default function SpaPage() {
  return (
    <table>
      <tbody>
        <For each={entries}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
              <td>
                <A href={`/spa/detail?id=${entry.id}`}>View →</A>
              </td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}
