// packages/app-react-router/app/routes/client-side-rendered.tsx
import { useState } from 'react'
import { Link } from 'react-router'

type Entry = { id: string; name: string }

function generateData(): Entry[] {
  return Array.from({ length: 1000 }, () => ({
    id: crypto.randomUUID(),
    name: crypto.randomUUID(),
  }))
}

export default function ClientSideRenderedPage() {
  const [entries] = useState(generateData)

  return (
    <table>
      <tbody>
        {entries.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <Link to={`/client-side-rendered/${entry.id}`}>View →</Link>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

// packages/app-nuxt/app/pages/client-side-rendered/index.vue
<script setup lang="ts">
type Entry = { id: string; name: string }

const entries: Entry[] = Array.from({ length: 1000 }, () => ({
  id: crypto.randomUUID(),
  name: crypto.randomUUID(),
}))
</script>

<template>
  <table>
    <tbody>
      <tr v-for="entry in entries" :key="entry.id">
        <td>{{ entry.id }}</td>
        <td>{{ entry.name }}</td>
        <td>
          <NuxtLink :to="`/client-side-rendered/${entry.id}`">View →</NuxtLink>
        </td>
      </tr>
    </tbody>
  </table>
</template>
