// packages/app-sveltekit/src/routes/+page.svelte
<script lang="ts">
  let { data } = $props()
</script>

<svelte:head>
  <title>SvelteKit SSR Benchmark</title>
</svelte:head>

<table>
  <tbody>
    {#each data.entries as entry}
      <tr>
        <td>{entry.id}</td>
        <td>{entry.name}</td>
        <td><a href={`/server-side-rendered/${entry.id}`}>View →</a></td>
      </tr>
    {/each}
  </tbody>
</table>

// packages/app-solid-start/src/routes/index.tsx
import { For } from 'solid-js'
import { query, createAsync } from '@solidjs/router'
import { testData } from '../../../testdata/src/ssr'

const getData = query(async () => {
  'use server'
  return await testData()
}, 'test-data')

export const route = {
  preload: () => getData(),
}

export default function Home() {
  const data = createAsync(() => getData())

  return (
    <table>
      <tbody>
        <For each={data()}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
              <td>
                <a href={`/server-side-rendered/${entry.id}`}>View →</a>
              </td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}
