// packages/app-tanstack-start-react/src/routes/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { getTestData } from '../data/test-data'
import type { TableEntry } from '../../../testdata/src/ssr'

export const Route = createFileRoute('/')({
  component: Home,
  loader: () => getTestData(),
})

function Home() {
  const data: TableEntry[] = Route.useLoaderData()

  return (
    <table>
      <tbody>
        {data.map((entry) => (
          <tr key={entry.id}>
            <td>{entry.id}</td>
            <td>{entry.name}</td>
            <td>
              <Link to="/server-side-rendered/$id" params={{ id: entry.id }}>
                View →
              </Link>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

// packages/app-solid-start/src/routes/index.tsx
import { For } from 'solid-js'
import { query, createAsync } from '@solidjs/router'
import { testData } from '../../../testdata/src/ssr'

const getData = query(async () => {
  'use server'
  return await testData()
}, 'test-data')

export const route = {
  preload: () => getData(),
}

export default function Home() {
  const data = createAsync(() => getData())

  return (
    <table>
      <tbody>
        <For each={data()}>
          {(entry) => (
            <tr>
              <td>{entry.id}</td>
              <td>{entry.name}</td>
              <td>
                <a href={`/server-side-rendered/${entry.id}`}>View →</a>
              </td>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  )
}
